# Generated by Django 2.2.1 on 2019-05-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexWord',
            fields=[
                ('word', models.TextField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('document_name', models.TextField(max_length=255, primary_key=True, serialize=False)),
                ('frequency', models.IntegerField()),
                ('indexes', models.TextField(max_length=255)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.IndexWord')),
            ],
        ),
    ]
